#pragma once
#define NOMINMAX
#define WIN32_LEAN_AND_MEAN
#include <Windows.h>
#include <ctime>
#include <iostream>
#include <fstream>
#include <time.h>
#include <cstdlib>
#include <string>
#include <tlhelp32.h>
#include <assert.h>
#include <lm.h>
#include <winuser.h>
#include <stdlib.h>
#include <stdio.h>
#include <future>
#include <algorithm>
#include <shlobj.h>
#include <direct.h>
#include <streambuf>
#include <thread>
#include <tchar.h>
#include <process.h>
#include <chrono>
#include <sstream>
#include <iomanip>
#include <string>
#include <vector>
#include <map>
#include <locale>
#include <codecvt>